OVERVIEW_COLUMN_WIDTH_MAPPING = {
    'A': 21,
    'B': 60,
    'C': 85,
    'D': 82,
    'E': 82,
    'F': 100,
    'G': 85,
    'H': 110,
    'I': 110,
    'J': 100,
    'K': 100,
    'L': 80,
    'M': 100,
    'N': 120,
    'O': 120,
    'P': 85,
    'Q': 85,
    'R': 85,
    'S': 95,
    'T': 75,
    'U': 100,
    'V': 100,
    'W': 95,
    'X': 85,
    'Y': 80,
    'Z': 21,
}
OVERVIEW_COLUMN_TITLES = [
    'Pre-Tax Earnings',
    'Salary',
    'Bonus',
    'Pre-Tax Deductions',
    'Taxes',
    'Retirement Fund Contribution',
    'HSA Contribution',
    'Post-Tax Deductions',
    'Total Deductions',
    'Net Pay',
    'Reimbursed Income',
    'Miscellaneous Income',
    'Total Income (Net to Account)',
    'Needs Spend',
    'Wants Spend',
    'Savings Spend',
    'Emergency Fund Spend',
    'Savings Saved',
    'Emergency Fund Saved',
    'Investments Saved',
    'Emergency Fund in HSA',
    'Total Spend',
    'Net Income',
]
YEARLY_CATEGORIES_COLUMN_WIDTH_MAPPING = {
    'A': 21,
    'B': 185,
    'C': 90,
    'D': 21,
    'E': 190,
    'F': 175,
    'G': 85,
    'H': 21,
    'I': 210,
    'J': 180,
    'K': 85,
    'L': 21,
    'M': 230,
    'N': 85,
    'O': 85,
    'P': 21,
}

CURRENCY_FORMAT = {
    'horizontalAlignment': 'RIGHT',
    'numberFormat': {
        'type': 'CURRENCY',
        'pattern': '[Color 10]$#,##0.00;[Color 9]($#,##0.00);$0.00',
    },
}
HEADER_FORMAT = {
    'horizontalAlignment': 'CENTER',
    'wrapStrategy': 'WRAP',
    'textFormat': {'fontSize': 12, 'bold': True},
}
HEADER_FORMAT_NO_WRAP = {
    'horizontalAlignment': 'CENTER',
    'textFormat': {'fontSize': 12, 'bold': True},
}
LEFT_ALIGN_PLAIN_TEXT = {
    'horizontalAlignment': 'LEFT',
    'hyperlinkDisplayType': 'PLAIN_TEXT',
}

OVERVIEW_MONTHLY_FORMAT = {
    'B2:Y2': HEADER_FORMAT,
    'B3:B': {
        'horizontalAlignment': 'RIGHT',
        'numberFormat': {'type': 'DATE', 'pattern': 'MM/yyyy'},
    },
    'C3:Y': CURRENCY_FORMAT,
}
OVERVIEW_YEARLY_FORMAT = {
    'B2:Y2': HEADER_FORMAT,
    'B3:B': {
        'horizontalAlignment': 'RIGHT',
    },
    'C3:Y': CURRENCY_FORMAT,
}
OVERVIEW_NOTES = {
    'C2': 'Gross Earnings',
    'E2': 'Includes Bonus, PTO Payout, and Severance',
    'F2': 'FSA and Medical',
    'G2': 'Medicare, Federal, State, City, NYPFL, Disability, and Social Security',
    'H2': 'Pre Tax or Roth',
    'J2': 'Critical Illness, AD & D, Long Term Disability',
    'K2': 'Pre-Tax Deductions + Taxes + HSA Contribution + Post-Tax Deductions',
    'L2': 'Gross Earnings - Total Deductions',
    'M2': 'Income for Items Reimbursed by Employer. Not counted in Total Income because the spend is categorized as a net zero expense category.',
    'N2': 'Any income not from an employer. Credit Card Cash Back, Selling items, gifts, etc.',
    'O2': 'Net Pay + Miscellaneous Income',
    'V2': 'Investment categories equal 0 at the end of the month and all money budgeted is invested.',
    'W2': 'Amount spent on items that can be reimbursed by the HSA, but have not been reimbursed yet. This money can be used for emergency expenses as a last resort.',
    'X2': 'Needs Spend + Wants Spend + Savings Spend + Emergency Fund Spend',
    'Y2': 'Total Income (Net to Account) - Total Spend',
}

YEARLY_CATEGORIES_FORMAT = {
    'B2:C2': HEADER_FORMAT_NO_WRAP,
    'C3:C': CURRENCY_FORMAT,
    'E2:G2': HEADER_FORMAT_NO_WRAP,
    'E3:F': LEFT_ALIGN_PLAIN_TEXT,
    'G3:G': CURRENCY_FORMAT,
    'I2:K2': HEADER_FORMAT_NO_WRAP,
    'I3:J': LEFT_ALIGN_PLAIN_TEXT,
    'K3:K': CURRENCY_FORMAT,
    'M2:O2': HEADER_FORMAT_NO_WRAP,
    'M3:M10': LEFT_ALIGN_PLAIN_TEXT,
    'N3:O10': CURRENCY_FORMAT,
    'M12:O12': HEADER_FORMAT_NO_WRAP,
    'M13:M18': LEFT_ALIGN_PLAIN_TEXT,
    'N13:O18': CURRENCY_FORMAT,
    'M20:O20': HEADER_FORMAT_NO_WRAP,
    'N21:O33': CURRENCY_FORMAT,
}
YEARLY_CATEGORIES_NOTES = {
    'B3': 'Gross Earnings',
    'B4': 'FSA and Medical',
    'B6': 'Includes Bonus, PTO Payout, and Severance',
    'B7': 'Medicare, Federal, State, City, NYPFL, Disability, and Social Security',
    'B8': 'Pre Tax or Roth',
    'B9': 'HSA Contribution',
    'B10': 'Critical Illness, AD & D, Long Term Disability',
    'B11': 'Pre-Tax Deductions + Taxes + HSA Contribution + Post-Tax Deductions',
    'B12': 'Gross Earnings - Total Deductions',
    'B13': 'Income for Items Reimbursed by Employer. Not counted in Total Income because the spend is categorized as a net zero expense category.',
    'B14': 'Any income not from an employer. Credit Card Cash Back, Selling items, gifts, etc.',
    'B15': 'Net Pay + Miscellaneous Income',
    'B16': 'Needs Spend + Wants Spend + Savings Spend + Emergency Fund Spend',
    'B17': 'Total Income (Net to Account) - Total Spend',
    'M8': 'Amount spent on items that can be reimbursed by the HSA, but have not been reimbursed yet. This money can be used for emergency expenses as a last resort.',
    'M17': 'Investment categories equal 0 at the end of the month and all money budgeted is invested.',
}
